image_analyzer:
  name: 图像分析
  description: 使用智谱GLM-4V模型分析图像
  fields:
    model:
      name: 模型
      description: '选择要使用的图像分析模型'
      required: true
      example: "glm-4v-flash"
      default: "glm-4v-flash"
      selector:
        select:
          options:
            - "glm-4v-plus"
            - "glm-4v"
            - "glm-4v-flash"
    message:
      name: 提示词
      required: true
      description: '给模型的提示词'
      example: "请描述这张图片的内容"
      selector:
        text:
          multiline: true
    image_file:
      name: 图片文件
      required: false
      description: '本地图片路径（支持jpg、png、jpeg格式，最大5MB，最大分辨率6000x6000像素）'
      example: "/config/www/tmp/front_door.jpg"
      selector:
        text:
          multiline: false
    image_entity:
      name: 图片实体
      required: false
      description: '要分析的图片或摄像头实体'
      example: 'camera.front_door'
      selector:
        entity:
          domain: ["image", "camera"]
          multiple: false
    temperature:
      name: 温度
      required: false
      description: '控制输出的随机性（0.1-1.0）。值越低，输出越稳定'
      example: 0.8
      default: 0.8
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
    max_tokens:
      name: 最大令牌数
      required: false
      description: '限制生成文本的最大长度'
      example: 1024
      default: 1024
      selector:
        number:
          min: 1
          max: 1024
          step: 1
    stream:
      name: 流式响应
      required: false
      description: '是否使用流式响应（实时返回生成结果）'
      example: false
      default: false
      selector:
        boolean: {}

video_analyzer:
  name: 视频分析
  description: 使用智谱GLM-4V-Plus模型分析视频
  fields:
    model:
      name: 模型
      description: '视频分析模型 (仅支持 GLM-4V-Plus)'
      required: false
      default: "glm-4v-plus"
      selector:
        select:
          options:
            - "glm-4v-plus"
    message:
      name: 提示词
      required: true
      description: '给模型的提示词'
      example: "请描述这段视频的内容"
      selector:
        text:
          multiline: true
    video_file:
      name: 视频文件
      required: true
      description: '本地视频文件路径（支持mp4格式，建议时长不超过30秒）'
      example: "/config/www/tmp/video.mp4"
      selector:
        text:
          multiline: false
    temperature:
      name: 温度
      required: false
      description: '控制输出的随机性（0.1-1.0）。值越低，输出越稳定'
      example: 0.8
      default: 0.8
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
    max_tokens:
      name: 最大令牌数
      required: false
      description: '限制生成文本的最大长度'
      example: 1024
      default: 1024
      selector:
        number:
          min: 1
          max: 1024
          step: 1
    stream:
      name: 流式响应
      required: false
      description: '是否使用流式响应（实时返回生成结果）'
      example: false
      default: false
      selector:
        boolean: {}

image_gen:
  name: 图像生成
  description: 使用 CogView-3 模型生成图像
  fields:
    prompt:
      name: 图像描述
      description: 所需图像的文本描述
      required: true
      example: "一只可爱的小猫咪"
      selector:
        text:
          multiline: true
    model:
      name: 模型
      description: 选择要使用的模型版本
      required: false
      default: cogview-3-flash
      selector:
        select:
          options:
            - label: CogView-3 Plus
              value: cogview-3-plus
            - label: CogView-3
              value: cogview-3
            - label: CogView-3 Flash (免费)
              value: cogview-3-flash
    size:
      name: 图片尺寸
      description: 生成图片的尺寸大小
      required: false
      default: 1024x1024
      selector:
        select:
          options:
            - label: 1024x1024
              value: 1024x1024
            - label: 768x1344
              value: 768x1344
            - label: 864x1152
              value: 864x1152
            - label: 1344x768
              value: 1344x768
            - label: 1152x864
              value: 1152x864
            - label: 1440x720
              value: 1440x720
            - label: 720x1440
              value: 720x1440

web_search:
  name: 联网搜索
  description: 使用智谱AI的web-search-pro工具进行联网搜索
  fields:
    query:
      name: 搜索内容
      description: '要搜索的内容'
      required: true
      example: "中国队奥运会拿了多少奖牌"
      selector:
        text:
          multiline: true
    stream:
      name: 流式响应
      description: '是否使用流式响应（实时返回生成结果）'
      required: false
      default: false
      selector:
        boolean: {}
