image_analyzer:
  name: 摄像分析 | Image Analysis
  description: 使用智谱GLM-4V模型分析摄像或图像 | Analyze images or videos using the Zhipuai GLM-4V model
  fields:
    model:
      name: 模型 | Model
      description: '选择要使用的图像分析模型 | Select the image analysis model to use'
      required: true
      example: "glm-4.1v-thinking-flash"
      default: "glm-4.1v-thinking-flash"
      selector:
        select:
          options:
            - "glm-4v-plus"
            - "glm-4v"
            - "glm-4v-flash"
            - "glm-4.1v-thinking-flash"
            - "glm-4.1v-thinking-flashX"
    message:
      name: 提示词 | Prompt
      required: true
      description: '给模型的提示词 | Prompt for the model'
      example: "请描述这张图片的内容 | Please describe the content of this image"
      selector:
        text:
          multiline: true
    image_file:
      name: 图片文件 | Image File
      required: false
      description: '本地图片路径（支持jpg、png、jpeg格式，最大5MB，最大分辨率6000x6000像素） | Local image path (supports jpg, png, jpeg formats, max 5MB, max resolution 6000x6000 pixels)'
      example: "/config/www/tmp/front_door.jpg"
      selector:
        text:
          multiline: false
    image_entity:
      name: 摄像头或图片实体 | Camera or Image Entity
      required: false
      description: '请选择要分析的实体 | Select the entity to analyze'
      example: 'camera.front_door'
      selector:
        entity:
          domain: ["image", "camera"]
          multiple: false
    temperature:
      name: 温度 | Temperature
      required: false
      description: '控制输出的随机性 0.1-1.0 值越低，输出越稳定 | Controls output randomness (0.1-1.0). Lower values produce more stable output.'
      example: 0.8
      default: 0.8
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
    max_tokens:
      name: 最大令牌数 | Max Tokens
      required: false
      description: '限制生成文本的最大长度 | Limit the maximum length of generated text'
      example: 1024
      default: 1024
      selector:
        number:
          min: 1
          max: 1024
          step: 1
    stream:
      name: 流式响应 | Stream Response
      required: false
      description: '是否使用流式响应（实时返回生成结果） | Whether to use stream response (return generated results in real-time)'
      example: false
      default: false
      selector:
        boolean: {}
    crop_ratio:
      name: 放大镜（进阶） | Crop Ratio (Advanced)
      required: false
      default: 0.5
      description: '暴露更多细节让AI分析，可以用作分析车牌号、人脸、手部细节等，本工具为裁切工具，会自动裁剪并图像中心区域到指定宽度，高度将按16:9比例自动调整。数值越小裁切越多，建议 0.4-0.8 为佳 | Expose more details for AI analysis, can be used for analyzing license plates, faces, hand details, etc. This tool is a cropping tool, which will automatically crop and adjust the image center area to the specified width, and the height will be adjusted automatically according to the 16:9 ratio. Lower values crop more, recommended 0.4-0.8.'
      example: 0.5
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
    save_frame:
      name: 保存分析帧（实验） | Save Analysis Frame (Experimental)
      required: false
      default: false
      description: '将分析的帧保存到 /www/zhipuai_cam 目录，现有文件将被覆盖。以作为自动化或脚本快速通知分析结果展示，也可以查看放大镜的图片效果 | Save the analyzed frame to the /www/zhipuai_cam directory, existing files will be overwritten. Can be used for automation or scripting to quickly notify analysis results, or to view the magnified image effect.'
      selector:
        boolean: {}

video_analyzer:
  name: 视频分析 | Video Analysis
  description: 使用智谱GLM-4V-Plus模型分析视频 | Analyze videos using the Zhipuai GLM-4V-Plus model
  fields:
    model:
      name: 模型 | Model
      description: '视频分析模型 (仅支持 GLM-4V-Plus) | Video analysis model (only supports GLM-4V-Plus)'
      required: false
      default: "glm-4v-plus"
      selector:
        select:
          options:
            - "glm-4v-plus"
    message:
      name: 提示词 | Prompt
      required: true
      description: '给模型的提示词 | Prompt for the model'
      example: "请描述这段视频的内容 | Please describe the content of this video"
      selector:
        text:
          multiline: true
    video_file:
      name: 视频文件 | Video File
      required: true
      description: '视频文件路径（支持mp4格式，最大50MB，最大分辨率6000x6000像素） | Video file path (supports mp4 format, max 50MB, max resolution 6000x6000 pixels)'
      example: "/config/www/tmp/video.mp4"
      selector:
        text:
          multiline: false
    crop_ratio:
      name: 裁切比例 | Crop Ratio
      required: false
      default: 0.5
      description: '设置中心区域裁切比例（0.1-1.0）。数值越小，裁切越多，放大倍数越大。例如：0.5表示裁切到原始尺寸的50%，0.3表示裁切到30%。 | Set center crop ratio (0.1-1.0). Lower values crop more and zoom in more. Example: 0.5 crops to 50% of original size, 0.3 crops to 30%.'
      example: 0.5
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
    temperature:
      name: 温度 | Temperature
      required: false
      description: '控制输出的随机性（0.1-1.0）。值越低，输出越稳定 | Controls output randomness (0.1-1.0). Lower values produce more stable output.'
      example: 0.8
      default: 0.8
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
    max_tokens:
      name: 最大令牌数 | Max Tokens
      required: false
      description: '限制生成文本的最大长度 | Limit the maximum length of generated text'
      example: 1024
      default: 1024
      selector:
        number:
          min: 1
          max: 1024
          step: 1
    stream:
      name: 流式响应 | Stream Response
      required: false
      description: '是否使用流式响应（实时返回生成结果） | Whether to use stream response (return generated results in real-time)'
      example: false
      default: false
      selector:
        boolean: {}

image_gen:
  name: 图像生成 | Image Generation
  description: 使用 CogView-3 模型生成图像 | Generate images using the CogView-3 model
  fields:
    prompt:
      name: 图像描述 | Image Description
      description: 所需图像的文本描述 | Text description of the desired image
      required: true
      example: "一只可爱的小猫咪 | A cute little cat"
      selector:
        text:
          multiline: true
    model:
      name: 模型 | Model
      description: 选择要使用的模型版本 | Select the model version to use
      required: false
      default: cogview-3-flash
      selector:
        select:
          options:
            - label: CogView-3 Plus
              value: cogview-3-plus
            - label: CogView-3
              value: cogview-3
            - label: CogView-3 Flash (免费)
              value: cogview-3-flash
    size:
      name: 图片尺寸 | Image Size
      description: 生成图片的尺寸大小 | Size of the generated image
      required: false
      default: 1024x1024
      selector:
        select:
          options:
            - label: 1024x1024
              value: 1024x1024
            - label: 768x1344
              value: 768x1344
            - label: 864x1152
              value: 864x1152
            - label: 1344x768
              value: 1344x768
            - label: 1152x864
              value: 1152x864
            - label: 1440x720
              value: 1440x720
            - label: 720x1440
              value: 720x1440

web_search:
  name: 联网搜索 | Web Search
  description: 使用智谱AI的Web Search API进行联网搜索 | Perform web search using Zhipuai AI's Web Search API
  fields:
    query:
      name: 搜索内容 | Search Query
      description: '要搜索的内容 | Search content'
      required: true
      example: "中国队奥运会拿了多少奖牌 | How many medals did the Chinese team win at the Olympics"
      selector:
        text:
          multiline: true
    search_engine:
      name: 搜索引擎 | Search Engine
      description: '选择要使用的搜索引擎类型 | Select the search engine type to use'
      required: false
      default: "search_std"
      example: "search_std"
      selector:
        select:
          options:
            - label: 智谱基础版搜索(免费至2025.5.31)
              value: search_std
            - label: 智谱高阶版搜索
              value: search_pro
            - label: 搜狗搜索
              value: search_pro_sogou
            - label: 夸克搜索
              value: search_pro_quark
            - label: Jina.AI搜索
              value: search_pro_jina
    time_query:
      name: 时间筛选 | Time Filter
      description: '添加时间筛选条件，如"2025年4月"、"最近一个月"、"今年上半年"等 | Add time filter conditions, such as "April 2025", "last month", "first half of this year", etc.'
      required: false
      example: "2025年4月 | April 2025"
      selector:
        text:
          multiline: false
    stream:
      name: 流式响应 | Stream Response
      description: '是否使用流式响应（实时返回生成结果） | Whether to use stream response (return generated results in real-time)'
      required: false
      default: false
      selector:
        boolean: {}

entity_analysis:
  name: 实体历史记录 | Entity History
  description: 获取实体的历史状态记录（如人在传感器、灯光、温度、湿度、光照度变化记录等） | Get the historical state records of entities (such as people in sensors, lights, temperature, humidity, illuminance changes, etc.)
  fields:
    entity_id:
      name: 实体ID | Entity ID
      description: 要获取历史记录的实体ID | Entity ID to get historical records for
      required: true
      selector:
        entity:
          multiple: true
    days:
      name: 天数 | Days
      description: 要获取的历史记录天数（1-15天） | Number of days to get historical records for (1-15 days)
      default: 3
      selector:
        number:
          min: 1
          max: 15
          mode: box

process_with_ha:
  name: 优先本地处理 | Prioritize Local Processing
  description: 尝试先使用 Home Assistant 本地处理，如果失败且则使用 智谱AI 处理。 | Try to use Home Assistant local processing first, if failed, then use Zhipuai AI processing.
  fields:
    text:
      name: 对话内容 | Conversation Content
      required: true
      description: '要处理的对话内容 | Conversation content to process'
      example: "打开客厅灯光 | Turn on living room lights"
      selector:
        text:
          multiline: true
    language:
      name: 语言 | Language
      required: false
      description: '对话语言，默认为中文 | Conversation language, default is Chinese'
      example: "zh-cn"
      default: "zh-cn"
      selector:
        text:
          multiline: true
    fallback_agent:
      name: 备用AI | Fallback AI
      required: false
      description: '如果本地处理失败，要使用的备用AI助手 | Fallback AI to use if local processing fails'
      example: "conversation.zhi_pu_qing_yan"
      selector:
        entity:
          domain: ["conversation"]
          multiple: false

generate_data:
  name: 生成数据 | Generate Data
  description: 使用智谱AI生成结构化数据，支持AI Task功能 | Generate structured data using Zhipuai AI, supports AI Task functionality
  fields:
    prompt:
      name: 提示词 | Prompt
      required: true
      description: '给智谱AI的提示词 | Prompt for Zhipuai AI'
      example: "请生成一个智能家居场景描述"
      selector:
        text:
          multiline: true
    model:
      name: 模型 | Model
      required: false
      description: '选择要使用的智谱AI模型 | Select the Zhipuai AI model to use'
      default: "glm-4"
      example: "glm-4"
      selector:
        select:
          options:
            - "glm-4"
            - "glm-4v"
            - "glm-3-turbo"
            - "chatglm_turbo"
            - "chatglm_pro"
            - "chatglm_std"
            - "chatglm_lite"
    temperature:
      name: 温度 | Temperature
      required: false
      description: '控制输出的随机性 0.1-1.0 值越低，输出越稳定 | Controls output randomness (0.1-1.0). Lower values produce more stable output.'
      example: 0.8
      default: 0.8
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
    max_tokens:
      name: 最大令牌数 | Max Tokens
      required: false
      description: '限制生成文本的最大长度 | Limit the maximum length of generated text'
      example: 1024
      default: 1024
      selector:
        number:
          min: 1
          max: 4096
          step: 1
    stream:
      name: 流式响应 | Stream Response
      required: false
      description: '是否使用流式响应（实时返回生成结果） | Whether to use stream response (return generated results in real-time)'
      example: false
      default: false
      selector:
        boolean: {}
