generate_image:
  name: 生成图像
  description: 使用智谱AI CogView模型生成图像
  fields:
    prompt:
      name: 提示词
      description: 描述要生成的图像内容
      required: true
      example: "一只可爱的猫咪坐在窗台上看夕阳"
      selector:
        text:
          multiline: true
    size:
      name: 图像尺寸
      description: 生成图像的尺寸
      required: false
      default: "1024x1024"
      selector:
        select:
          options:
            - "1024x1024"
            - "768x1344"
            - "864x1152"
            - "1344x768"
            - "1152x864"
            - "1440x720"
            - "720x1440"
    model:
      name: 模型
      description: 使用的图像生成模型
      required: false
      default: "cogview-3-flash"
      selector:
        select:
          options:
            - "cogview-3-flash"
            - "cogview-3"
            - "cogview-3-plus"
