name: Validate with hassfest

on:
  push:
    paths-ignore:
      - '.github/workflows/**'




jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: home-assistant/actions/hassfest@master
