name: Release

on:
  release:
    types: [published]
  # 仅当推送内容不包含 workflow 文件时才触发本流程（即 workflow 文件有变更时不触发）
  push:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: zip custom component
        run: |
          cd ${{ github.workspace }}/custom_components/zhipuai
          zip -r zhipuai.zip ./

      - name: upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/zhipuai/zhipuai.zip
          asset_name: zhipuai.zip
          tag: ${{ github.ref }}
          overwrite: true